# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Taesung Kwon
title: Bio Imaging, Signal Processing & Learning Lab (BISPL), KAIST AI.
email: star.kwon@kaist.ac.kr
website: https://star-kwon.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
linkedin_username: star-kwon
# github_username: star-kwon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google-scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=Mv9KjrsAAAAJ&hl=en
- title: CV
  icon: fa fa-file
  url: https://drive.google.com/file/d/1D8gQQAlGwzJtGMga9WBuGMiDYdbndsu3/view?usp=drive_link

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Taesung and I'm a fourth-year Ph.D. candidate in KAIST, advised by Prof. Jong Chul Ye and Prof. Mooseok Jang.
  During my Ph.D., I was a research intern at Disney Research Studios in Zurich.
  My research focuses on **computer vision (CV)** and its intersection with **generative models**, exploring their applications in solving inverse problems and enhancing image and video processing.
  My recent research aims to improve the **conditional generative process** by controlling the diffusion generative process. 
  Additionally, I explore methods to leverage **temporal correlations** to improve the performance of inverse problem solvers.

  My research spans three key areas, including but not limited to:

  * **Generative Models**: Diffusion models for video inverse problems, video frame interpolation, and image generation/editing.

  * **Low-Level Vision**: Unsupervised and self-supervised denoising techniques for both images and videos.
  
  * **Physics-Based Vision and Medical Imaging**: Applications to physical sciences (e.g., inverse scattering in optics) and medical imaging.
 
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: KAIST
        caption: "Advisors: Jong Chul Ye and Mooseok Jang"
        sub_title: Ph.D. Candidate in Bio and Brain Engineering
        quote: >
          2022 - Current
      - layout: top-middle
        title: KAIST
        caption: "Advisor: Jong Chul Ye"
        sub_title: M.S. in Bio and Brain Engineering
        quote: >
          2020 - 2022
      - layout: top-middle
        title: KAIST
        caption: "Advisor: Yoonkey Nam"
        sub_title: B.S. in Bio and Brain Engineering
        quote: >
          2015 - 2020

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Disney Research
        caption: "Mentor: Vinicius Azevedo"
        sub_title: Research Internship @ Zürich
        quote: >
          2025.05 - 2025.08
      - layout: top-middle
        title: ETH Zürich
        caption: "Joint research program with Disney Research"
        sub_title: Visiting Researcher
        quote: >
          2025.05 - 2025.08

  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "Zero4D: Training-Free 4D Video Generation From Single Video Using Off-the-Shelf Video Diffusion Model"
        link: https://zero4dvid.github.io/
        description: | # this will include new lines to allow paragraphs
          J. Park, **Taesung Kwon**, J. C. Ye

          arXiv, 2025
          
          Zero-shot 4D video generation using off-the-shelf video diffusion model.
      - layout: left
        title: "VISION-XL: High Definition Video Inverse Problem Solver using Latent Diffusion Models"
        link: https://vision-xl.github.io/
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          **ICCV 2025**
          
          Solving HD video inverse problems using only latent diffusion models. Supporting wide-range ratio using SDXL.
      - layout: left
        title: "ViBiDSampler: Enhancing Video Interpolation Using Bidirectional Diffusion Sampler"
        link: https://vibidsampler.github.io/
        description: | # this will include new lines to allow paragraphs
          S. Yang\*, **Taesung Kwon\***, J. C. Ye **(*co-first)**

          **ICLR 2025**
          
          State-of-the-art performance, efficiently generating high-quality, smooth videos between keyframes.
      - layout: left
        title: "Solving Video Inverse Problems Using Image Diffusion Models"
        link: https://svi-diffusion.github.io/
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          **ICLR 2025**
          
          Solving video inverse problems using only image diffusion models, with batch-consistent sampling stretagy.
      - layout: left
        title: "Video Diffusion Posterior Sampling for Seeing Beyond Dynamic Scattering Layers"
        link: https://github.com/star-kwon/VDPS
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon\***, G. Song\*, Y. Kim, J. Kim, J. C. Ye, M. Jang **(*co-first)**

          **IEEE TPAMI**
          
          Video reconstruction through dynamic scattering layer using video diffusion models.
      - layout: left
        title: "Highly Personalized Text Embedding for Image Manipulation by Stable Diffusion"
        link: https://hiper0.github.io/
        description: | # this will include new lines to allow paragraphs
          I. Han\*, S. Yang\*, **Taesung Kwon**, J. C. Ye

          arXiv, 2023
          
          Image manipulation using personalized text embedding from Stable Diffusion.
      - layout: left
        title: "DiffusionCLIP: Text-Guided Diffusion Models for Robust Image Manipulation"
        link: https://github.com/gwang-kim/DiffusionCLIP
        description: | # this will include new lines to allow paragraphs
          G. Kim, **Taesung Kwon**, J. C. Ye

          **CVPR 2022**
          
          Robust text-driven image manipulation using text-to-image diffusion models.
      - layout: left
        title: "Noise Distribution Adaptive Self-Supervised Image Denoising using Tweedie Distribution and Score Matching"
        link: https://github.com/cubeyoung/NoiseAdaptive2Score
        description: | # this will include new lines to allow paragraphs
          K. Kim, **Taesung Kwon**, J. C. Ye

          **CVPR 2022**
          
          Noise distribution and level adaptive denoising framework using Tweedie distribution and score matching.
      - layout: left
        title: "Cycle-free CycleGAN using Invertible Generator for Unsupervised Low-Dose CT Denoising"
        link: https://github.com/star-kwon/TCI_CyclefreeCycleGAN
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          **IEEE TCI**
          
          Efficient CycleGAN framework for low-dose CT denoising.
      
          
  - title: Workshop # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "NTIRE 2022 Spectral Recovery Challenge and Data Set"
        description: | # this will include new lines to allow paragraphs
          **CVPRW 2022**
          
          Recovering hyperspectral information from JPEG-compressed RGB images.
      - layout: left
        title: "NTIRE 2022 Challenge on Night Photography Rendering"
        description: | # this will include new lines to allow paragraphs
          **CVPRW 2022**
          
          Recovering the visual appearance of night photography.

  - title: Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Method and Apparatus for Low-Dose X-Ray Computed Tomography Image Processing Based on Efficient Unsupervised Learning Using Invertible Neural Network**

      J. C. Ye, **Taesung Kwon**

      U.S. Patent, Granted, No. 12,346,997, 2025

      Korean Patent, Granted, No. 10-2643601, 2024

      - **Method and Apparatus for Generating Intermediate Video Frames via Bidirectional Sampling**

      J. C. Ye, S. Yang, **Taesung Kwon**

      Korean Patent, Filed, No. 10-2025-0114505, 2025
      
  - title: Awards and Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **KAIST Scholarship**, KAIST, 2022-2025
      - **Korean Government Scholarship**, KAIST, 2020-2021

  - title: Media Coverage
  layout: text
  content: | # this will include new lines to allow paragraphs
    - **TPAMI Research featured on YTN News (a major Korean news channel)**, 2025 [youtube](https://youtu.be/xi39viK9ozo?si=qHd42ChSkWjmeIn9)

  - title: Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Conference reviewers**: CVPR, ICLR, ICCV, ECCV, ICML
      - **Journal reviewers**: IEEE Transactions on Computational Imaging
      - **Lab Manager**, BISPL, 2024

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
