title: Taesung Kwon
position: Postdoctoral Researcher
affiliation: Graduate School of AI, KAIST
email: star.kwon (at) kaist.ac.kr
keywords: Computer Vision (CV), Machine Learning (ML), Signal Processing (SP)
google_scholar: https://scholar.google.com/citations?user=Mv9KjrsAAAAJ&hl=en
github_link: https://github.com/star-kwon
cv_link: https://drive.google.com/file/d/1D8gQQAlGwzJtGMga9WBuGMiDYdbndsu3/view?usp=drive_link
linkedin: https://www.linkedin.com/in/star-kwon/
avatar: ./assets/img/tsk.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/star.png
favicon_dark: ./assets/img/star.png
description: Taesung's blog
canonical: https://star-kwon.github.io/
remote_theme: star-kwon/star-kwon.github.io
