# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Taesung Kwon
title: Bio Imaging, Signal Processing & Learning Lab (BISPL), KAIST AI.
email: star.kwon@kaist.ac.kr
website: https://star-kwon.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
linkedin_username: star-kwon
github_username: star-kwon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google-scholar
  icon: fab fa-google-scholar
  url: https://scholar.google.com/citations?user=Mv9KjrsAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Taesung and I'm a third-year Ph.D. candidate in KAIST, advised by Prof. Jong Chul Ye and Prof. Mooseok Jang. My research focuses on artificial intelligence (AI), particularly in computer vision (CV) and its intersection with Diffusion models. I'm driven to leverage capabilities of diffuion models to solve wide-range of inverse problems.

  My work explores three key areas:

  * Video Inverse Problems (Deblur, Super-resolution, Inpaint)

  * Video Frame Interpolation

  * Inverse Scattering in Optics
  
  Also, I'm interested in computational imaging, and weakly- and self-supervised learning.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: KAIST
        caption: "Advisors: Jong Chul Ye and Mooseok Jang"
        sub_title: Ph.D. Candidate in Bio and Brain Engineering
        quote: >
          2022 - Current

      - layout: top-middle
        title: KAIST
        caption: "Advisor: Jong Chul Ye"
        sub_title: M.S. in Bio and Brain Engineering
        quote: >
          2020 - 2022
          
      - layout: top-middle
        title: KAIST
        caption: "Advisor: Yoonkey Nam"
        sub_title: B.S. in Bio and Brain Engineering
        quote: >
          2015 - 2020

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "VISION-XL: High Definition Video Inverse Problem Solver using Latent Diffusion Models"
        link: https://vision-xl.github.io/
        quote: >
          **Taesung Kwon** and J. C. Ye
        description: | # this will include new lines to allow paragraphs
          Solving HD video inverse problems using only latent diffusion models. Supporting wide-range ratio using SDXL.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Awards and Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **KAIST Scholarship**, KAIST, 2022-2024
      - **Korean Government Scholarship**, KAIST, 2020-2021

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
