# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Taesung Kwon
title: Bio Imaging, Signal Processing & Learning Lab (BISPL), KAIST AI.
email: star.kwon@kaist.ac.kr
website: https://star-kwon.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
linkedin_username: star-kwon
# github_username: star-kwon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google-scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=Mv9KjrsAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Taesung and I'm a fourth-year Ph.D. candidate in KAIST, advised by Prof. Jong Chul Ye and Prof. Mooseok Jang. My research focuses on artificial intelligence (AI), particularly in computer vision (CV) and its intersection with Diffusion models. I'm driven to leverage capabilities of diffuion models to solve wide-range of inverse problems.

  My work explores three key areas:

  * Video Inverse Problems (Deblur, Super-resolution, Inpaint)

  * Video Frame Interpolation

  * Real-world Inverse Problems (Inverse Scattering in Optics)
  
  Also, I'm interested in computational imaging, and weakly- and self-supervised learning.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: KAIST
        caption: "Advisors: Jong Chul Ye and Mooseok Jang"
        sub_title: Ph.D. Candidate in Bio and Brain Engineering
        quote: >
          2022 - Current
      - layout: top-middle
        title: KAIST
        caption: "Advisor: Jong Chul Ye"
        sub_title: M.S. in Bio and Brain Engineering
        quote: >
          2020 - 2022
      - layout: top-middle
        title: KAIST
        caption: "Advisor: Yoonkey Nam"
        sub_title: B.S. in Bio and Brain Engineering
        quote: >
          2015 - 2020

  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "VISION-XL: High Definition Video Inverse Problem Solver using Latent Diffusion Models"
        link: https://vision-xl.github.io/
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          arXiv, 2024
          
          Solving HD video inverse problems using only latent diffusion models. Supporting wide-range ratio using SDXL.
      - layout: left
        title: "ViBiDSampler: Enhancing Video Interpolation Using Bidirectional Diffusion Sampler"
        link: https://vibidsampler.github.io/
        description: | # this will include new lines to allow paragraphs
          S. Yang\*, **Taesung Kwon\***, J. C. Ye **(*co-first)**

          arXiv, 2024
          
          State-of-the-art performance, efficiently generating high-quality, smooth videos between keyframes.
      - layout: left
        title: "Solving Video Inverse Problems Using Image Diffusion Models"
        link: https://svi-diffusion.github.io/
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          arXiv, 2024
          
          Solving video inverse problems using only image diffusion models, with batch-consistent sampling stretagy.
      - layout: left
        title: "Video Reconstruction Beyond Dynamic Scattering Medium"
        link: https://github.com/star-kwon/VDPS
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon\***, G. Song\*, Y. Kim, J. Kim, J. C. Ye, M. Jang **(*co-first)**

          Submitted to TPAMI
          
          Video reconstruction through dynamic scattering layer using video diffusion models.
      - layout: left
        title: "Highly Personalized Text Embedding for Image Manipulation by Stable Diffusion"
        link: https://hiper0.github.io/
        description: | # this will include new lines to allow paragraphs
          I. Han\*, S. Yang\*, **Taesung Kwon**, J. C. Ye

          arXiv, 2023
          
          Image manipulation using personalized text embedding from Stable Diffusion.
      - layout: left
        title: "DiffusionCLIP: Text-Guided Diffusion Models for Robust Image Manipulation"
        link: https://github.com/gwang-kim/DiffusionCLIP
        description: | # this will include new lines to allow paragraphs
          G. Kim, **Taesung Kwon**, J. C. Ye

          **CVPR, 2022**
          
          Robust text-driven image manipulation using text-to-image diffusion models.
      - layout: left
        title: "Noise Distribution Adaptive Self-Supervised Image Denoising using Tweedie Distribution and Score Matching"
        link: https://github.com/cubeyoung/NoiseAdaptive2Score
        description: | # this will include new lines to allow paragraphs
          K. Kim, **Taesung Kwon**, J. C. Ye

          **CVPR, 2022**
          
          Noise distribution and level adaptive denoising framework using Tweedie distribution and score matching.
      - layout: left
        title: "Cycle-free CycleGAN using Invertible Generator for Unsupervised Low-Dose CT Denoising"
        link: https://github.com/star-kwon/TCI_CyclefreeCycleGAN
        description: | # this will include new lines to allow paragraphs
          **Taesung Kwon**, J. C. Ye

          **IEEE TCI, 2021**
          
          Efficient CycleGAN framework for low-dose CT denoising.
      
          
  - title: Workshop # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "NTIRE 2022 Spectral Recovery Challenge and Data Set"
        description: | # this will include new lines to allow paragraphs
          **CVPRW, 2022**
          
          Placed 9th out of 241 teams in a competition. Recovering hyperspectral information from JPEG-compressed RGB images.
      - layout: left
        title: "NTIRE 2022 Challenge on Night Photography Rendering"
        description: | # this will include new lines to allow paragraphs
          **CVPRW, 2022**
          
          Placed 11th with 1,197 votes for visual preference, out of a total of 3,250 votes. Recovering the visual appearance of night photography.

  - title: Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Method and Apparatus for Low-Dose X-Ray Computed Tomography Image Processing Based on Efficient Unsupervised Learning Using Invertible Neural Network**

      J. C. Ye, **Taesung Kwon**

      U.S. Patent Application, Filed, No. 17/848,689, 2022

      Korean Patent, Granted, No. 10-2643601, 2024
      
  - title: Awards and Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **KAIST Scholarship**, KAIST, 2022-2024
      - **Korean Government Scholarship**, KAIST, 2020-2021

  - title: Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Conference reviewers**: CVPR, NeurIPS, ICLR, ICCV
      - **Journal reviewers**: IEEE TCI

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
